{% set name = "hyp3_sdk" %}
{% set version = "7.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfef425b5a58f96b81a13645dd688a06dd490d32312b247393d7681661fef7fd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=6.2
    - python-build
  run:
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - tqdm
    - urllib3

test:
  requires:
    - python {{ python_min }}
  imports:
    - hyp3_sdk
    - hyp3_sdk.jobs
    - hyp3_sdk.hyp3
    - hyp3_sdk.util
    - hyp3_sdk.exceptions

about:
  home: https://github.com/ASFHyP3/hyp3-sdk
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A python wrapper around the HyP3 API

extra:
  recipe-maintainers:
    - andrewplayer3
    - jhkennedy
    - asjohnston-asf
    - jtherrmann
    - jacquelynsmale
    - forrestfwilliams
